name: Collect properties - Homes

on:
  schedule:
    - cron: '0 6 * * 5'  # Friday 6:00 UTC (18:00, 19:00 New Zealand)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      NEON_DB: ${{ secrets.NEON_DB }}
      PYTHONPATH: . 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python properties/get_homes_by_suburb.py
          python -u internet_outage/get_broadband_availability.py &
          PID1=$!
          python -u properties/get_land_tax.py &
          PID2=$!
          python -u properties/get_homes_detail.py &
          PID3=$!
          wait $PID1 $PID2 $PID3
