name: Collect crime count - Crime Stats NZ

on:
  schedule:
    - cron: '0 0 1 * *'  # Once every month
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      NEON_DB: ${{ secrets.NEON_DB }}
      PYTHONPATH: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run the script
        run: |
          python crime/check_suburbs.py
          check_suburbs_result=$?
          if [ "$check_suburbs_result" -eq 3 ]; then
              python population/suburbs.py
          fi
          python crime/get_crime.py